-- Paradise City shared sessions: state persistence + human/agent chat.
-- This preserves room-code capability access used by the original multiplayer design.

create table if not exists public.game_rooms (
  room_code text primary key,
  city_name text not null,
  game_state text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  player_count integer not null default 1,
  created_by uuid null references auth.users(id) on delete set null
);

create table if not exists public.game_room_messages (
  id bigint generated by default as identity primary key,
  room_code text not null references public.game_rooms(room_code) on delete cascade,
  sender_id text not null,
  sender_name text not null,
  sender_type text not null check (sender_type in ('human', 'agent', 'system')),
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists game_room_messages_room_created_idx
  on public.game_room_messages (room_code, created_at desc);

alter table public.game_rooms enable row level security;
alter table public.game_room_messages enable row level security;

drop policy if exists "Paradise shared rooms" on public.game_rooms;
create policy "Paradise shared rooms"
  on public.game_rooms for all
  using (true)
  with check (true);

drop policy if exists "Paradise shared chat" on public.game_room_messages;
create policy "Paradise shared chat"
  on public.game_room_messages for all
  using (true)
  with check (true);

create or replace function public.touch_game_room_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists game_rooms_touch_updated_at on public.game_rooms;
create trigger game_rooms_touch_updated_at
before update on public.game_rooms
for each row execute function public.touch_game_room_updated_at();
